export interface IVehicle {
  id: number;
  make: string; // Марка
  model: string; // Модель
  year: number; // Год выпуска
  registration: {
    number: string; // Регистрационный номер
    country: string; // Страна регистрации
    state: string; // Регион регистрации
  };
  type: 'Truck' | 'Van' | 'Car' | 'Bike' | 'Other'; // Статус: в работе, на ремонте и т.д.
  status: 'Waits' | 'Works' | 'Repairs' | 'NotInUse' | 'Utilized'; // Тип: грузовик, фургон, автомобиль и т.д.
  load_capacity?: number; // Грузоподъемность в килограммах (необязательное)
}

export const VehiclesList: IVehicle[] = [
  {
    id: 1,
    make: 'Ford',
    model: 'Transit',
    year: 2018,
    registration: {
      number: 'AB123CD',
      country: 'RU',
      state: 'Moscow',
    },
    type: 'Van',
    status: 'Works',
    load_capacity: 1500,
  },
  {
    id: 2,
    make: 'Volvo',
    model: 'FH16',
    year: 2020,
    registration: {
      number: 'EF456GH',
      country: 'SE',
      state: 'Stockholm',
    },
    type: 'Truck',
    status: 'Works',
    load_capacity: 20000,
  },
  {
    id: 3,
    make: 'Toyota',
    model: 'Corolla',
    year: 2019,
    registration: {
      number: 'IJ789KL',
      country: 'JP',
      state: 'Tokyo',
    },
    type: 'Car',
    status: 'Waits',
  },
  {
    id: 4,
    make: 'Yamaha',
    model: 'YZF-R3',
    year: 2017,
    registration: {
      number: 'MN123OP',
      country: 'JP',
      state: 'Osaka',
    },
    type: 'Bike',
    status: 'Works',
  },
  {
    id: 5,
    make: 'Mercedes-Benz',
    model: 'Actros',
    year: 2021,
    registration: {
      number: 'QR456ST',
      country: 'DE',
      state: 'Berlin',
    },
    type: 'Truck',
    status: 'Works',
    load_capacity: 25000,
  },
  {
    id: 6,
    make: 'Volkswagen',
    model: 'Caddy',
    year: 2022,
    registration: {
      number: 'UV789WX',
      country: 'DE',
      state: 'Hamburg',
    },
    type: 'Van',
    status: 'Waits',
    load_capacity: 800,
  },
  {
    id: 7,
    make: 'Honda',
    model: 'Civic',
    year: 2016,
    registration: {
      number: 'YZ123AB',
      country: 'US',
      state: 'California',
    },
    type: 'Car',
    status: 'Repairs',
  },
  {
    id: 8,
    make: 'MAN',
    model: 'TGX',
    year: 2019,
    registration: {
      number: 'CD456EF',
      country: 'DE',
      state: 'Munich',
    },
    type: 'Truck',
    status: 'Works',
    load_capacity: 22000,
  },
  {
    id: 9,
    make: 'Piaggio',
    model: 'Ape',
    year: 2015,
    registration: {
      number: 'GH789IJ',
      country: 'IT',
      state: 'Milan',
    },
    type: 'Other',
    status: 'Works',
    load_capacity: 300,
  },
  {
    id: 10,
    make: 'Hyundai',
    model: 'H350',
    year: 2018,
    registration: {
      number: 'KL123MN',
      country: 'KR',
      state: 'Seoul',
    },
    type: 'Van',
    status: 'Repairs',
    load_capacity: 1000,
  },
  {
    id: 11,
    make: 'Renault',
    model: 'Master',
    year: 2017,
    registration: {
      number: 'OP123QR',
      country: 'FR',
      state: 'Paris',
    },
    type: 'Van',
    status: 'Works',
    load_capacity: 1200,
  },
  {
    id: 12,
    make: 'Scania',
    model: 'R450',
    year: 2021,
    registration: {
      number: 'ST456UV',
      country: 'SE',
      state: 'Gothenburg',
    },
    type: 'Truck',
    status: 'Works',
    load_capacity: 25000,
  },
  {
    id: 13,
    make: 'Chevrolet',
    model: 'Camaro',
    year: 2016,
    registration: {
      number: 'WX789YZ',
      country: 'US',
      state: 'Texas',
    },
    type: 'Car',
    status: 'NotInUse',
  },
  {
    id: 14,
    make: 'Suzuki',
    model: 'GSX-R1000',
    year: 2015,
    registration: {
      number: 'AB123CD',
      country: 'JP',
      state: 'Nagoya',
    },
    type: 'Bike',
    status: 'Works',
  },
  {
    id: 15,
    make: 'Iveco',
    model: 'Daily',
    year: 2019,
    registration: {
      number: 'EF456GH',
      country: 'IT',
      state: 'Rome',
    },
    type: 'Van',
    status: 'Works',
    load_capacity: 1500,
  },
  {
    id: 16,
    make: 'Nissan',
    model: 'NV400',
    year: 2020,
    registration: {
      number: 'IJ789KL',
      country: 'JP',
      state: 'Osaka',
    },
    type: 'Van',
    status: 'Waits',
    load_capacity: 1400,
  },
  {
    id: 17,
    make: 'Kawasaki',
    model: 'Ninja H2',
    year: 2018,
    registration: {
      number: 'MN123OP',
      country: 'JP',
      state: 'Yokohama',
    },
    type: 'Bike',
    status: 'Works',
  },
  {
    id: 18,
    make: 'BMW',
    model: 'X5',
    year: 2017,
    registration: {
      number: 'QR456ST',
      country: 'DE',
      state: 'Munich',
    },
    type: 'Car',
    status: 'Waits',
  },
  {
    id: 19,
    make: 'Tesla',
    model: 'Model S',
    year: 2020,
    registration: {
      number: 'UV789WX',
      country: 'US',
      state: 'California',
    },
    type: 'Car',
    status: 'Works',
  },
  {
    id: 20,
    make: 'Mercedes-Benz',
    model: 'Sprinter',
    year: 2021,
    registration: {
      number: 'YZ123AB',
      country: 'DE',
      state: 'Stuttgart',
    },
    type: 'Van',
    status: 'Repairs',
    load_capacity: 1300,
  },
  {
    id: 21,
    make: 'Mitsubishi',
    model: 'Fuso',
    year: 2019,
    registration: {
      number: 'GH789IJ',
      country: 'JP',
      state: 'Yokohama',
    },
    type: 'Truck',
    status: 'Works',
    load_capacity: 18000,
  },
  {
    id: 22,
    make: 'Peugeot',
    model: 'Boxer',
    year: 2017,
    registration: {
      number: 'KL123MN',
      country: 'FR',
      state: 'Lyon',
    },
    type: 'Van',
    status: 'Waits',
    load_capacity: 1100,
  },
  {
    id: 23,
    make: 'Audi',
    model: 'A6',
    year: 2018,
    registration: {
      number: 'OP456QR',
      country: 'DE',
      state: 'Berlin',
    },
    type: 'Car',
    status: 'Works',
  },
  {
    id: 24,
    make: 'Harley-Davidson',
    model: 'Street Glide',
    year: 2016,
    registration: {
      number: 'ST789UV',
      country: 'US',
      state: 'Florida',
    },
    type: 'Bike',
    status: 'Works',
  },
  {
    id: 25,
    make: 'Fiat',
    model: 'Doblo',
    year: 2018,
    registration: {
      number: 'WX123YZ',
      country: 'IT',
      state: 'Naples',
    },
    type: 'Van',
    status: 'Repairs',
    load_capacity: 1000,
  },
];
